- name: deploy corosync.conf
  template:
    src: corosync.conf.j2
    dest: /etc/corosync/corosync.conf

- name: deploy haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
