- name: stop firewalld
  systemd:
    name: firewalld
    enabled: no
    state: stop

- name: start pcsd
  systemd:
    name: pcsd
    enabled: yes
    state: started

- name: start haproxy
  systemd:
    name: haproxy
    enabled: yes
    state: started